language: rust
rust:
  - nightly
services:
  - postgresql
cache:
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/backend/target
install:
  - "cargo install diesel_cli"
before_script:
  - "cd $TRAVIS_BUILD_DIR/backend"
  - "mv travis.env .env"
  - "diesel setup"
  - "diesel migration run"
script:
  - "cd $TRAVIS_BUILD_DIR/backend"
  - "cargo test -- --test-threads=1"
