language: rust
rust:
  - nightly
services:
  - postgresql
env:
  - "DATABASE_URL=postgres://postgres@localhost/laggit"
    # Disable concurrent tests
  - "RUST_TEST_THREADS=1"
install:
  - "cargo install diesel_cli"
before_script:
  - "cd $TRAVIS_BUILD_DIR/backend"
  - "diesel setup"
  - "diesel migration run"
script:
  - "cd $TRAVIS_BUILD_DIR/backend"
  - "cargo test"
