language: rust

rust:
  - stable

services:
  - postgresql

cache:
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/backend/target

install:
  - "cargo install diesel_cli || true"

before_script:
  - "cd $TRAVIS_BUILD_DIR/backend"
  - "mv travis.env .env"
  - "diesel setup"
  - "diesel migration run"

script:
    # Test backend
  - "cd $TRAVIS_BUILD_DIR/backend"
  - "cargo test -- --test-threads=1"

    # Test common
  - "cd $TRAVIS_BUILD_DIR/common"
  - "cargo test"

    # Test frontend
  - "cd $TRAVIS_BUILD_DIR/frontend"
  - "cargo test"
