language: rust
rust:
  - nightly
services:
  - postgresql

install:
  - "cargo install diesel_cli"
before_script:
  - "cd $TRAVIS_BUILD_DIR/backend"
  - "diesel setup"
  - "diesel migration run"
script:
  - "cd $TRAVIS_BUILD_DIR/backend"
  - "cargo test"
