[package]
name = "laggit_backend"
version = "0.1.0"
authors = ["Joakim Hulthe <joakim@hulthe.net>"]

[dependencies]
rocket = "0.3.16"
rocket_codegen = "0.3.16"
rocket_contrib = "0.3.16"
diesel = { version = "1.0.0", features = ["postgres", "chrono"] }
dotenv = "0.9.0"
serde = "1.0.79"
serde_derive = "1.0.79"
chrono = { version = "0.4.6", features = ["serde"] }

